In [1]:
import numpy as np
import pandas as pd

from pathlib import Path
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
%load_ext autoreload
%autoreload 2

In [3]:
import pickle

In [4]:
from sleep_analysis.datasets.mesadataset import MesaDataset

In [5]:
test_idx_list = ['0027',
 '0077',
 '0111',
 '0169',
 '0193',
 '0197',
 '0204',
 '0269',
 '0306',
 '0372',
 '0388',
 '0393',
 '0408',
 '0474',
 '0526',
 '0548',
 '0586',
 '0599',
 '0672',
 '0683',
 '0807',
 '0856',
 '0889',
 '0921',
 '0923',
 '0934',
 '0935',
 '0962',
 '0967',
 '0968',
 '1080',
 '1113',
 '1164',
 '1187',
 '1209',
 '1294',
 '1297',
 '1308',
 '1395',
 '1453',
 '1474',
 '1476',
 '1497',
 '1502',
 '1552',
 '1563',
 '1570',
 '1584',
 '1589',
 '1620',
 '1672',
 '1677',
 '1704',
 '1707',
 '1735',
 '1766',
 '1768',
 '1797',
 '1821',
 '1844',
 '1856',
 '1874',
 '1878',
 '1884',
 '1921',
 '1964',
 '2003',
 '2043',
 '2119',
 '2139',
 '2145',
 '2163',
 '2193',
 '2251',
 '2279',
 '2372',
 '2388',
 '2397',
 '2429',
 '2464',
 '2519',
 '2604',
 '2614',
 '2659',
 '2685',
 '2701',
 '2738',
 '2762',
 '2780',
 '2820',
 '2834',
 '2913',
 '2930',
 '2952',
 '2987',
 '2988',
 '2995',
 '3003',
 '3006',
 '3028',
 '3053',
 '3066',
 '3094',
 '3104',
 '3112',
 '3224',
 '3297',
 '3317',
 '3337',
 '3344',
 '3352',
 '3375',
 '3415',
 '3423',
 '3486',
 '3516',
 '3520',
 '3529',
 '3537',
 '3622',
 '3630',
 '3634',
 '3656',
 '3664',
 '3690',
 '3717',
 '3745',
 '3760',
 '3793',
 '3795',
 '3803',
 '3855',
 '3892',
 '3971',
 '3974',
 '3976',
 '4017',
 '4128',
 '4190',
 '4199',
 '4240',
 '4277',
 '4301',
 '4330',
 '4334',
 '4379',
 '4394',
 '4480',
 '4488',
 '4500',
 '4515',
 '4541',
 '4563',
 '4580',
 '4592',
 '4641',
 '4648',
 '4677',
 '4723',
 '4729',
 '4777',
 '4826',
 '4888',
 '4980',
 '5002',
 '5006',
 '5009',
 '5096',
 '5103',
 '5104',
 '5131',
 '5167',
 '5261',
 '5292',
 '5298',
 '5304',
 '5318',
 '5351',
 '5362',
 '5393',
 '5427',
 '5440',
 '5532',
 '5550',
 '5608',
 '5656',
 '5680',
 '5722',
 '5784',
 '5792',
 '5847',
 '5882',
 '5888',
 '5896',
 '5906',
 '6000',
 '6009',
 '6027',
 '6029',
 '6050',
 '6115',
 '6205',
 '6262',
 '6274',
 '6280',
 '6291',
 '6292',
 '6298',
 '6306',
 '6311',
 '6333',
 '6384',
 '6460',
 '6462',
 '6501',
 '6509',
 '6566',
 '6610',
 '6632',
 '6671',
 '6697',
 '6726',
 '6784',
 '6807']
with open('test_idx.pkl', 'wb') as f:
    pickle.dump(test_idx_list, f)

In [6]:
dataset = MesaDataset()
test_subj = dataset.get_subset(mesa_id = test_idx_list)

In [7]:
#test_set_info = [subj.information for subj in test_subj]

In [8]:
#df_test_info = pd.concat(test_set_info, axis=1)
#df_test_info = df_test_info.T
#df_test_info.columns.name = "info"
#df_test_info = df_test_info.rename(columns={'race1c':'race',
#                                 "gender1":"gender",
#                                 "sleepage5c":"age",
#                                 "overall5":"PSG_quality",
#                                 "whiirs5c": "WHIIRS_score",
#                                 "slpapnea5":"sleep_apnea",
#                                 "insmnia5":"insomnia",
#                                 "rstlesslgs5":"resstles_legs",
#                                 "actquality5":"quality_actigraphy",
#                                 "ahi_a0h4": "AH-Index",
#                                 "extrahrs5":"extra_work_hours"})
#df_test_info.index.name = "subject"
#df_test_info.to_pickle("mesa_test_info.pkl")
#df_test_info

In [10]:
df_test_info = pd.read_pickle("../mesa_test_info.pkl")
df_test_info

info,race,gender,PSG_quality,WHIIRS_score,sleep_apnea,insomnia,resstles_legs,age,AH-Index,extra_work_hours
subject,,,,,,,,,,
2388,1.0,0.0,7.0,5.0,0.0,0.0,0.0,63.0,2.640587,0.0
0548,4.0,1.0,5.0,1.0,0.0,0.0,0.0,70.0,4.332604,0.0
2834,2.0,1.0,5.0,9.0,0.0,0.0,0.0,78.0,25.900990,0.0
1497,3.0,1.0,7.0,10.0,1.0,0.0,0.0,65.0,60.702576,0.0
2820,2.0,0.0,5.0,3.0,0.0,0.0,0.0,56.0,1.141304,0.0
...,...,...,...,...,...,...,...,...,...,...
3104,1.0,0.0,5.0,17.0,0.0,1.0,0.0,63.0,0.923077,0.0
0169,1.0,1.0,7.0,5.0,0.0,0.0,0.0,71.0,38.033898,5.0
2193,1.0,1.0,6.0,9.0,1.0,0.0,1.0,76.0,27.543860,0.0
4723,2.0,0.0,5.0,14.0,0.0,0.0,0.0,77.0,6.935484,0.0
0586,4.0,0.0,5.0,13.0,0.0,0.0,0.0,58.0,0.151134,0.0

In [11]:
train_idx_list = list(set(dataset.index["mesa_id"]) - set(test_idx_list))

In [12]:
train_subj = dataset.get_subset(mesa_id = train_idx_list)

In [ ]:
#train_set_info = [subj.information for subj in train_subj]

In [ ]:
#df_train_info = pd.concat(train_set_info, axis=1)
#df_train_info = df_train_info.T
#df_train_info.columns.name = "info"
#df_train_info = df_train_info.rename(columns={'race1c':'race',
#                                 "gender1":"gender",
#                                 "sleepage5c":"age",
#                                 "overall5":"PSG_quality",
#                                 "whiirs5c": "WHIIRS_score",
#                                 "slpapnea5":"sleep_apnea",
#                                 "insmnia5":"insomnia",
#                                 "rstlesslgs5":"resstles_legs",
#                                 "actquality5":"quality_actigraphy",
#                                 "ahi_a0h4": "AH-Index",
#                                 "extrahrs5":"extra_work_hours"})
#df_train_info.index.name = "subject"
#df_train_info.to_pickle("mesa_train_info.pkl")
#df_train_info

In [13]:
df_train_info = pd.read_pickle("../mesa_train_info.pkl")
df_train_info

info,race,gender,PSG_quality,WHIIRS_score,sleep_apnea,insomnia,resstles_legs,age,AH-Index,extra_work_hours
subject,,,,,,,,,,
3914,1.0,0.0,6.0,8.0,0.0,0.0,0.0,59.0,1.722488,8.0
1859,3.0,0.0,7.0,6.0,0.0,0.0,0.0,76.0,4.169884,0.0
4935,3.0,0.0,6.0,10.0,0.0,1.0,1.0,56.0,3.354037,0.0
2377,2.0,0.0,5.0,7.0,0.0,0.0,0.0,62.0,0.664820,12.0
4706,1.0,1.0,5.0,6.0,0.0,0.0,0.0,80.0,1.265823,0.0
...,...,...,...,...,...,...,...,...,...,...
4284,2.0,1.0,4.0,8.0,0.0,1.0,0.0,84.0,17.166213,0.0
2434,1.0,0.0,5.0,7.0,0.0,0.0,0.0,83.0,5.909091,0.0
1673,1.0,0.0,6.0,13.0,0.0,0.0,0.0,69.0,12.272727,0.0
5373,3.0,1.0,6.0,3.0,0.0,0.0,0.0,76.0,75.660377,0.0
6685,1.0,1.0,5.0,5.0,0.0,0.0,0.0,69.0,21.818182,0.0

## Age

In [14]:
#Train:
df_train_info.agg(["mean", "std"])

info,race,gender,PSG_quality,WHIIRS_score,sleep_apnea,insomnia,resstles_legs,age,AH-Index,extra_work_hours
mean,2.191964,0.460938,5.569196,6.962054,0.071429,0.064732,0.045759,68.467634,13.279467,1.993304
std,1.243073,0.498750,0.933372,4.382381,0.257683,0.246190,0.209079,8.814606,15.113939,4.954988

In [15]:
# Test:
df_test_info.agg(["mean", "std"])

info,race,gender,PSG_quality,WHIIRS_score,sleep_apnea,insomnia,resstles_legs,age,AH-Index,extra_work_hours
mean,2.348214,0.415179,5.558036,7.397321,0.066964,0.035714,0.044643,68.450893,14.163903,2.044643
std,1.221701,0.493856,0.896544,4.438740,0.250520,0.185992,0.206981,8.440629,15.631285,5.678831

## Gender

In [16]:
# Train
df_train_info["gender"].value_counts()

0.0    483
1.0    413
Name: gender, dtype: int64

In [17]:
# Test
df_test_info["gender"].value_counts()

0.0    131
1.0     93
Name: gender, dtype: int64